CREATE TABLE turma (
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
modulo VARCHAR(255) DEFAULT 0
);
CREATE TABLE estudante (
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
data_nasc DATE NOT NULL,
turma_id VARCHAR(255) NOT NULL,
FOREIGN KEY(turma_id) REFERENCES turma(id)
);
CREATE TABLE docente (
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
data_nasc DATE NOT NULL,
turma_id VARCHAR(255) NOT NULL,
FOREIGN KEY(turma_id) REFERENCES turma(id)
);
CREATE TABLE hobby (
id VARCHAR(255) PRIMARY KEY,
nome VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE estudante_hobby (
id VARCHAR(255) PRIMARY KEY,
estudante_nome VARCHAR(255) NOT NULL,
hobby_nome VARCHAR(255) NOT NULL,
FOREIGN KEY(estudante_nome) REFERENCES estudante(nome),
FOREIGN KEY(hobby_nome) REFERENCES hobby(nome)
);
